name: PAPWALK-CI

permissions:
  contents: write

defaults:
  run:
    working-directory: papwalk

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAPWALK_PAT }}

      - name: Set Flutter version
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.32.5'
        
      - name: Install project dependencies
        run: flutter pub get

      - name: Generate supporting files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Enable windows build
        run: flutter config --enable-windows-desktop

      - name: Build portable
        run: flutter build windows --release

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: papwalk-${{github.ref_name}}-windows.zip
          directory: papwalk/build/windows/x64/runner/Release
        
      - name: Build MSIX
        run: dart run msix:create --install-certificate false

      - name: Rename Output
        shell: pwsh
        run: Move-Item -Path .\build\windows\x64\runner\Release\papwalk.msix -Destination .\build\windows\x64\runner\Release\papwalk-${{github.ref_name}}.msix

      - name: Windows Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            papwalk/build/windows/x64/runner/Release/papwalk-${{github.ref_name}}-windows.zip
            papwalk/build/windows/x64/runner/Release/papwalk-${{github.ref_name}}.msix

